name: CI/CD React App to Droplet

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 4. Remove old dist folder contents
      - name: Clean old dist
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          script: |
            echo "Removing old dist contents..."
            rm -rf /var/www/arbilo/arbilo-frontends/dist/*
            echo "Old dist removed."

      # 5. Copy new build to droplet
      - name: Copy dist to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          source: "dist/*"       # copy contents only
          target: "/var/www/arbilo/arbilo-frontends/dist"

      # 6. Set proper permissions
      - name: Set permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          script: |
            echo "Setting permissions..."
            chown -R www-data:www-data /var/www/arbilo/arbilo-frontends/dist
            chmod -R 755 /var/www/arbilo/arbilo-frontends/dist
            echo "Deployment finished successfully ✅"
