name: CI/CD Arbilo App to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository (needed for GitHub Actions context)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Show latest commit for logging
      - name: Show latest commit
        run: git log -1 --oneline

      # 3️⃣ Delete old project, clone fresh, install, and build
      - name: Full project refresh and build on droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          script: |
            echo "Deleting old project folder..."
            rm -rf /var/www/arbilo/arbilo-frontends
            echo "Old project deleted."

            echo "Cloning fresh project from GitHub..."
            git clone https://github.com/readyiolab/arbilo-frontend.git /var/www/arbilo/arbilo-frontends
            cd /var/www/arbilo/arbilo-frontends

            echo "Installing dependencies..."
            npm ci

            echo "Building React app..."
            npm run build

            echo "Setting permissions..."
            chown -R www-data:www-data /var/www/arbilo/arbilo-frontends
            chmod -R 755 /var/www/arbilo/arbilo-frontends

            echo "Deployment finished successfully ✅"
